name: autonomous_fund
author: balancer
version: 0.1.0
description: A set of agents implementing the Autonomous Fund.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint:
  README.md: bafybeicdyhjhou5zymkztgxubvtzwwrldmzbhophrmtkubnuoh7pbwpcsq
fingerprint_ignore_patterns: []
agent: balancer/autonomous_fund:0.1.0:bafybeigw2ghyywgygfbcymtr4vm6didxhq2ariwhq3inxi3gzqvx5ts2qm
number_of_agents: 4
---
public_id: balancer/autonomous_fund_abci:0.1.0
type: skill
models:
  params:
    args:
      setup:
        safe_contract_address: ${SKILL_AUTONOMOUS_FUND_ABCI_MODELS_PARAMS_ARGS_SETUP_SAFE_CONTRACT_ADDRESS:list:["0xD1A2679e3455a018d9e0D11edb873e7C5B5d831e"]}
      managed_pool_address: ${SKILL_AUTONOMOUS_FUND_ABCI_MODELS_PARAMS_ARGS_MANAGED_POOL_ADDRESS:str:0xE7718Db6786516f426cC72673088e628Ac4721A1}
      managed_pool_controller_address: ${SKILL_AUTONOMOUS_FUND_ABCI_MODELS_PARAMS_ARGS_MANAGED_POOL_CONTROLLER_ADDRESS:str:0x7017752b993958d7b4e65bf68a08c7833840f1e8}
      consensus:
        max_participants: 4
      observation_interval: 300
      reset_tendermint_after: 5
---
public_id: valory/ledger:0.19.0
type: connection
config:
  0:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_0:str:http://127.0.0.1:8545}
        chain_id: 5
  1:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_1:str:http://127.0.0.1:8545}
        chain_id: 5
  2:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_2:str:http://127.0.0.1:8545}
        chain_id: 5
  3:
  - ledger_apis:
      ethereum:
        address: ${SERVICE_AUTONOMOUS_FUND_RPC_3:str:http://127.0.0.1:8545}
        chain_id: 5
