agent_name: autonomous_fund
author: balancer
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.19.0, <2.0.0'
fingerprint:
  __init__.py: bafybeialdpvrelsxfu7zh5r5s7tg3gpcz3kc33snhifzdlvjj6rssbzspa
  tests/__init__.py: bafybeicmv3jjcqcdnmubfmrgdgeyic3nkm77z4mutsyuo34hpddwupofre
  tests/helpers/__init__.py: bafybeiauwuw4a4wxqacqqkkk52ktps2qedadhypvh3ex7uqs7qaqrpygmy
  tests/helpers/constants.py: bafybeiailsgona66kndd6lrnqpclwb2dczpkinqzrtzpqfmyql5nvpz6aq
  tests/helpers/docker.py: bafybeif6d6ku7ljgmcwfy6ogo7jm2x6mwxkwsp7gb4lbk3xijduui5humi
  tests/helpers/fixtures.py: bafybeigcajxzps6jijodtylnabncov53egj26zzng6tsj3ymr43kec7igq
  tests/test_contracts/__init__.py: bafybeiel4den34ewkgjdlze2gdw5veayz3xtnnii4tfznjltpq33nsssda
  tests/test_contracts/test_managed_pool_controller/__init__.py: bafybeid3fa64f4rskt4tf6hfjxqzid2o5dopuh2f53aegclg6fj5ylso5i
  tests/test_contracts/test_managed_pool_controller/test_contract.py: bafybeic5dvc6nvm3oadkzuifeg7o5pz4mab54asojpleph3alolrpkcswq
fingerprint_ignore_patterns: []
connections: []
contracts:
- balancer/managed_pool_controller:0.1.0:bafybeifg72vduvwtwmrdjzm42az3cp4wdhqf3f6q2mr7vzxyvpcznf3kqi
- balancer/weighted_pool:0.1.0:bafybeiakmkvywhq3fyotbxyxd4w2ie2mlebg4kpi2k3orfbt4yaxtryez4
protocols:
- open_aea/signing:1.0.0:bafybeifexbtq3cqrodkmy75djq7hck5c44jnjezywins7fzzg5nn6yi6om
skills: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
